- name: Install required packages
  apt:
    name:
      - wget
      - ca-certificates
      - python3-psycopg2
    update_cache: true

- name: Add PostgreSQL official APT repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL official APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: true

- name: Install PostgreSQL
  apt:
    name: postgresql-17
    update_cache: true

- name: Create database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ lookup('env', 'POSTGRESQL_DATABASE') }}"
    port: "{{ lookup('env', 'POSTGRESQL_PORT') }}"
    encoding: 'utf8'

- name: Create PostgreSQL user
  become_user: postgres
  community.postgresql.postgresql_user:
    db: "{{ lookup('env', 'POSTGRESQL_DATABASE') }}"
    name: "{{ lookup('env', 'POSTGRESQL_USERNAME') }}"
    password: "{{ lookup('env', 'POSTGRESQL_PASSWORD') }}"
    port: "{{ lookup('env', 'POSTGRESQL_PORT') }}"
    encrypted: true
    
- name: Configure PostgreSQL for remote access
  become_user: postgres
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: '*'
    port: "{{ lookup('env', 'POSTGRESQL_PORT') }}"

- name: Configure pg_hba.conf for remote access
  lineinfile:
    path: /etc/postgresql/17/main/pg_hba.conf
    line: "host all all 0.0.0.0/0 trust"
    state: present

- name: Setup PostgreSQL timeZone
  lineinfile:
    path: /etc/postgresql/17/main/postgresql.conf
    regexp: "^#?TimeZone =.*"
    line: "TimeZone = 'Europe/Kyiv'"

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted