- name: Install PostgreSQL
  apt:
    name: postgresql-17
    update_cache: true

- name: Create database
  become_user: postgres
  postgresql_db:
    name: "{{ lookup('env', 'POSTGRESQL_DATABASE') }}"
    port: "{{ lookup('env', 'POSTGRESQL_PORT') }}"
    encoding: 'utf8'

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    db: "{{ lookup('env', 'POSTGRESQL_DATABASE') }}"
    name: "{{ lookup('env', 'POSTGRESQL_USERNAME') }}"
    password: "{{ lookup('env', 'POSTGRESQL_PASSWORD') }}"
    expires: 'infinity'
    
- name: Configure PostgreSQL for remote access
  become_user: postgres
  postgresql_conf:
    name: listen_addresses
    value: '*'
    state: present

- name: Configure pg_hba.conf for remote access
  lineinfile:
    path: /etc/postgresql/17/main/pg_hba.conf
    line: "host all all 0.0.0.0/0 trust"
    state: present

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted