name: Apply database migrations

on:
  workflow_run:
    workflows: ["Check and install PostgreSQL"]
    types: [completed]
    branches: [prod]

jobs:
  apply-main-database-migrations:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: 'Prisma Migrate'
        run: npx prisma migrate deploy --schema ./db/postgresql/schema.prisma
        env:
          ANINAME_POSTGRES_URL: postgresql://${{ secrets.POSTGRESQL_USERNAME }}:${{ secrets.POSTGRESQL_PASSWORD }}@${{ secrets.SERVER_HOST }}:${{ secrets.POSTGRESQL_PORT }}/${{ secrets.POSTGRESQL_DATABASE }} 