name: Deploy to prod environment

on:
  push:
    branches: [prod]

jobs:
  apply-main-database-migrations:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Prisma Migrate'
        run: npx prisma migrate deploy --schema ./db/postgresql/schema.prisma
        env:
          ANINAME_POSTGRES_URL: ${{ secrets.ANINAME_POSTGRES_URL }}
