name: Deploy to prod environment

on:
  push:
    branches: [prod]
    paths: ['docker-compose.yml', '.github/workflows/deploy-prod.yml']

jobs:
  install-or-update:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Update apt-get
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo apt-get update -y
            sudo apt-get upgrade -y

      - name: Install/Update Git
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            if ! [ -x "$(command -v git)" ]; then
              echo "Install Git..."
              sudo apt-get install git -y
            else
              echo "Update Git..."
              sudo apt-get install --only-upgrade git -y
            fi

      - name: Install/Update Docker
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            if ! [ -x "$(command -v docker)" ]; then
              echo "Install Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            else
              echo "Update docker..."
              apt-get install --only-upgrade docker-ce docker-ce-cli containerd.io -y
            fi

      - name: Install Docker Compose if not installed
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            if ! [ -x "$(command -v docker-compose)" ]; then
              echo "Install Docker Compose..."
              curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
            fi

  upload:
    needs: install-or-update
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload db
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: 'db/postgresql'
          target: '/root'

  start-database:
    needs: upload
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: 'Start docker-compose'
        uses: appleboy/ssh-action@master

        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/db/postgresql
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            docker-compose up -d

  apply-migrations:
    needs: start-database
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: 'Apply migrations'
        uses: appleboy/ssh-action@master

        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/db/postgresql
            export POSTGRES_URL="postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.SERVER_HOST }}:5432/${{ secrets.POSTGRES_DB }}"
            npx -y prisma migrate deploy
            