name: Deploy to prod environment

on:
  push:
    branches: [prod]

jobs:
  apply-main-database-migrations:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: 'Prisma Migrate'
        run: npx prisma migrate deploy --preview-feature
        env:
          ANINAME_POSTGRES_URL: ${{ secrets.ANINAME_POSTGRES_URL }}
      
            