name: PostgreSQL Setup

on:
  push:
    branches: [prod]

jobs:
  setup-postgresql:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Check PostgreSQL
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            if ! which psql > /dev/null; then
              apt update && apt install -y postgresql-17
              systemctl start postgresql
            fi

      - name: Terraform Apply
        working-directory: terraform/postgresql
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="db_host=${{ secrets.SERVER_HOST }}" \
            -var="app_user=${{ secrets.POSTGRESQL_USERNAME }}" \
            -var="app_password=${{ secrets.POSTGRESQL_PASSWORD }}" \
            -var="app_db=${{ secrets.POSTGRESQL_DATABASE }}"
