name: Create PostgreSQL DB and User

on:
  push:
    branches: [prod]

jobs:
  create-db:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Create Terraform variables file
        run: |
          cat > terraform/postgresql/terraform.tfvars <<EOF
          db_host         = "${{ secrets.DB_HOST }}"
          db_admin_user   = "${{ secrets.DB_ADMIN_USER }}"
          db_admin_password = "${{ secrets.DB_ADMIN_PASSWORD }}"
          app_user        = "${{ secrets.APP_USER }}"
          app_password    = "${{ secrets.APP_PASSWORD }}"
          app_db          = "${{ secrets.APP_DB }}"
          EOF

      - name: Terraform Init
        working-directory: terraform/postgresql
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/postgresql
        run: terraform apply -auto-approve
